/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddResourceToConfig: typeof import('./src/components/AddResourceToConfig.vue')['default']
    AddZipResourceComponent: typeof import('./src/components/AddZipResourceComponent.vue')['default']
    AIAddResourceManuallComponent: typeof import('./src/components/AIAddResourceManuallComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    ClusterGraph: typeof import('./src/components/ClusterGraph.vue')['default']
    ClusterRadarChart: typeof import('./src/components/ClusterRadarChart.vue')['default']
    CodeLine: typeof import('./src/components/fileDisplaying/CodeLine.vue')['default']
    CodePanel: typeof import('./src/components/fileDisplaying/CodePanel.vue')['default']
    ComparisonsTable: typeof import('./src/components/ComparisonsTable.vue')['default']
    ComparisonTableFilter: typeof import('./src/components/ComparisonTableFilter.vue')['default']
    ConfigListComponent: typeof import('./src/components/ConfigListComponent.vue')['default']
    ContainerComponent: typeof import('./src/components/ContainerComponent.vue')['default']
    CreatePlagConfigComponent: typeof import('./src/components/CreatePlagConfigComponent.vue')['default']
    DistributionDiagram: typeof import('./src/components/distributionDiagram/DistributionDiagram.vue')['default']
    DistributionDiagramOptions: typeof import('./src/components/distributionDiagram/DistributionDiagramOptions.vue')['default']
    DropDownComponent: typeof import('./src/components/DropDownComponent.vue')['default']
    DropDownSelector: typeof import('./src/components/DropDownSelector.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    FilesContainer: typeof import('./src/components/fileDisplaying/FilesContainer.vue')['default']
    GitAddResourceManuallyComponent: typeof import('./src/components/GitAddResourceManuallyComponent.vue')['default']
    GitUploadComponent: typeof import('./src/components/GitUploadComponent.vue')['default']
    InteractableComponent: typeof import('./src/components/InteractableComponent.vue')['default']
    LoadingCircle: typeof import('./src/components/LoadingCircle.vue')['default']
    LoadResourceComponent: typeof import('./src/components/LoadResourceComponent.vue')['default']
    ManuallyAddResourcesComponent: typeof import('./src/components/ManuallyAddResourcesComponent.vue')['default']
    MatchList: typeof import('./src/components/fileDisplaying/MatchList.vue')['default']
    MetricSelector: typeof import('./src/components/optionsSelectors/MetricSelector.vue')['default']
    NameElement: typeof import('./src/components/NameElement.vue')['default']
    OptionComponent: typeof import('./src/components/optionsSelectors/OptionComponent.vue')['default']
    OptionsSelectorComponent: typeof import('./src/components/optionsSelectors/OptionsSelectorComponent.vue')['default']
    PlagConfigDetailComponent: typeof import('./src/components/PlagConfigDetailComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunListComponent: typeof import('./src/components/RunListComponent.vue')['default']
    ScrollableComponent: typeof import('./src/components/ScrollableComponent.vue')['default']
    SearchBarComponent: typeof import('./src/components/SearchBarComponent.vue')['default']
    StartComparisonComponent: typeof import('./src/components/StartComparisonComponent.vue')['default']
    TabbedContainer: typeof import('./src/components/TabbedContainer.vue')['default']
    TextInformation: typeof import('./src/components/TextInformation.vue')['default']
    ToastComponent: typeof import('./src/components/ToastComponent.vue')['default']
    ToolTipComponent: typeof import('./src/components/ToolTipComponent.vue')['default']
    UploadFileComponent: typeof import('./src/components/UploadFileComponent.vue')['default']
    UploadFileModalComponent: typeof import('./src/components/UploadFileModalComponent.vue')['default']
    VersionInfoComponent: typeof import('./src/components/VersionInfoComponent.vue')['default']
    VersionRepositoryReference: typeof import('./src/components/VersionRepositoryReference.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
