name: dipl

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - fastapi
  - openai
  - python-dotenv
  - pydantic
  - numpy
  - pillow
  - starlette
  - requests
  - pip:
      - -e /Users/ibilobrk/razno/compare50git/compare50