package com.fer.projekt.utils

val edgarSubjects: Map<String, String> = mapOf(
    "2006" to "Objektno orijentirano programiranje",
    "2004" to "Uvod u programiranje",
    "2021" to "Razvoj programske potpore za web",
    "155" to "Baze podataka",
    "2012" to "Napredni algoritmi i strukture podataka",
    "477" to "Napredne baze podataka",
    "2022" to "Operacijska istraživanja",
    "866" to "Informacijski sustavi",
    "2017" to "Napredni razvoj programske potpore za web",
    "2020" to "Poslovna inteligencija",
    "2026" to "Zaštita i sigurnost informacijskih sustava",
    "2000" to "Alchemy",
    "2015" to "Object Oriented Programming",
    "328" to "Razvoj primijenjene programske potpore",
    "2013" to "Introduction to Programming",
    "2024" to "Web Software Development",
    "2002" to "Databases",
    "2001" to "Programsko inženjerstvo",
    "2035" to "Ofenzivna sigurnost",
    "2034" to "Sigurnosne prijetnje na Internetu",
    "2036" to "Sigurnost operacijskih sustava i aplikacija",
    "2007" to "Natjecateljsko programiranje",
    "2025" to "Introduction to programming (COGSCI)",
    "2019" to "Development of Software Applications",
    "2023" to "Business Intelligence",
    "2033" to "Sigurnost računalnih sustava",
    "2032" to "Computational Modeling Challenge",
    "2018" to "Algorithms and Data Structures",
    "2031" to "Objektno orijentirano programiranje",
    "2030" to "Informatika (Python)",
    "2011" to "Algoritmi",
    "1150" to "Upravljanje projektima",
    "2005" to "_Poslovna inteligencija (FER2)",
    "2014" to "Hack It",
    "2016" to "Sustavi baza podataka",
    "2003" to "Information Systems",
    "2008" to "Objektno orijentirano programiranje (FER2)",
    "2010" to "Dani otvorenih vrata",
    "2009" to "Smotra",
    "20" to "Algoritmi i strukture podataka",
    "2" to "Algoritmi i strukture podataka (FER 1)",
    "11" to "Programiranje i programsko inženjerstvo"
)
